/*
Please refer to readme.html for full Instructions

Text[...]=[title,text]

Style[...]=[TitleColor,TextColor,TitleBgColor,TextBgColor,TitleBgImag,TextBgImag,TitleTextAlign,TextTextAlign, TitleFontFace, TextFontFace, TipPosition, StickyStyle, TitleFontSize, TextFontSize, Width, Height, BorderSize, PadTextArea, CoordinateX , CoordinateY, TransitionNumber, TransitionDuration, TransparencyLevel ,ShadowType, ShadowColor]
*/
var FiltersEnabled = 1 // if your not going to use transitions or filters in any of the tips set this to 0
 
 var t0 ="<class='text'>При частоте основной гармоники выпрямленного напряжения <em class=index>u</em><em class=indexsmall>в</em> сопротивление конденсатора <em>С</em>-фильтра (рис. 5.25, <em>а</em>), включенного параллельно активной нагрузке <em>R</em>, должно быть значительно меньше сопротивления нагрузки, т.е. <img src='page5_8_1_3/221_clip_image002_0001.gif' width='115' height='25' align='absmiddle'>, где <em>n</em>- номер основной гармоники напряжения на выходе выпрямителя; <em class='symbol'>w </em>- уг ловая частота синусоидального напряжения. Коэффициент сглаживания <em>k</em><span class='indexsmall'><em>с</em></span>&nbsp;=&nbsp;<em class='index'>R</em>/<em class='index'>X</em><span class='indexsmall'><em>C</em></span><em></em>&nbsp;=&nbsp;<em>n</em><span class='symbol'><em>w</em></span><em>CR</em>. Из выражения <em>k</em><span class='indexsmall'><em>с</em></span><em> </em> видно, что <em>С </em>-фильтр целесобразно использовать при относительно высокоомной нагрузке <em>R</em>,"+
"например, для питания рентгеновской вакуумной трубки. <blockquote>Требуемая ёмкость конденсатора при заданном <em>k</em><em class='indexsmall'>с </em>: <em>С &#8805;</em> 2<img src='page5_8_1_3/221_clip_image002_0002.gif' width='72' height='24' align='absmiddle'> .</blockquote>"

 var t1 ="<class='text'>При частоте основной гармоники выпрямленного напряжения сопротивление индуктивной катушки (дросселя) <em class='index'>L </em>-фильтра (рис. 5.25, <em>б </em>), включенной последовательно с нагрузкой, должно быть значительно больше её сопротивления <em class='index'>R </em>, т.е. <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img src='page5_8_1_3/122_clip_image002_0005.gif' width='94' height='23' align='absmiddle'>.<br> Коэффициент сглаживания <em>k</em><span class='indexsmall'><em>с</em></span><em> = </em> <img src='page5_8_1_3/122_clip_image002_0001.gif' width='116' height='22' align='absmiddle'> . Видно, что в мощных выпрямителях (когда сопротивление <em>R </em> мало) фильтр действует наиболее эффективно. Требуемая индуктивность дросселя при заданном <em class='index'>k</em><em class='indexsmall'>с</em>: <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<em class='index'>L </em> = <img src='page5_8_1_3/122_clip_image002_0002.gif' width='72' height='23' align='absmiddle'> ."
 var t2 ="<class='text' ><p>В <span class='index'><em>LС </em>-</span>фильтре (рис. 5.25, <em>в</em>) конденсатор <em class='index'>С </em> шунтирует нагрузку по переменной составляющей (<img src='page5_8_1_3/11_clip_image002_0005.gif' width='23' height='22' align='absmiddle'>   = 1/<em class='index'>n </em><span class='symbol'><em>w</em></span><span class='index'><em>C</em></span><em> &lt;&lt; <span class='index'>R</span></em>), а сопротивление<img src='page5_8_1_3/11_clip_image002_0006.gif' width='22' height='21' align='absmiddle'>  должно быть значительно больше параллельно соединённых сопротивлений <em>R </em> и <strong></strong><img src='page5_8_1_3/11_clip_image002_0005.gif' width='23' height='22' align='absmiddle'>. Приняв сопротивление <img src='page5_8_1_3/11_clip_image002_0007.gif' width='67' height='26' align='absmiddle'> и <em>k<span class='indexsmall'>с</span> </em><span class='symbol'>»</span>"+ 
"<img src='page5_8_1_3/11_clip_image002_0006.gif'width='22'height='21'align='absmiddle'>/<img src='page5_8_1_3/11_clip_image002_0005.gif' width='23' height='22' align='absmiddle'> = <img src='page5_8_1_3/11_clip_image002_0008.gif' width='61' height='26' align='absmiddle'>, по известному коэффициенту <span class='index'>k</span><span class='indexsmall'><em>с</em></span>  находим произведение <em>LC</em>, а по заданной ёмкости <em class='index'>С </em> - индуктивность фильтра <em><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;L </em> = <em class='index'>k</em><em class='indexsmall'>с</em>/(<span class=index>n</span><span class=symbol>w</span><span class=indexbig>2</span>)<span class=index>C</span>. <br>Во избежание резонанса (при <img src='page5_8_1_3/11_clip_image002_0006.gif' width='22' height='21' align='absmiddle'>= <img src='page5_8_1_3/11_clip_image002_0005.gif' width='23' height='22' align='absmiddle'>) должно выполняться условие: "+
"<img src='page5_8_1_3/11_clip_image002.gif' width='152' height='28' align='absmiddle'></blockquote></p>"

 var t3 ="<class='text'><p>Если при расчёте <em>LC </em>-фильтра получают слишком большие значения индуктивности (<em>L </em> &gt; 100 Гн) дросселя и ёмкости (<em>С </em> &gt; 150 мкФ) конденсатора, то применяют двухзвенный <em>Г</em>-образный <em>RC</em>-фильтр (рис. 5.25, <em>г</em>), у которого <em class='index'>k</em><em class='indexsmall'>с</em>&nbsp;=&nbsp;<em class='index'>k</em><em class='indexsmall'>с</em><span class='indexsmaldigit'>1</span><span class='index'><em>k</em></span><span class='indexsmall'><em>с</em></span><span class='indexsmaldigit'>2</span>, где <span class='index'><em>k</em></span><em class='indexsmall'>с</em><span class='indexsmaldigit'>1</span> и <em>k<span class='indexsmall'>с</span></em><span class='indexsmaldigit'>2</span> - соответственно коэффициенты сглаживания первого и второго звеньев. </p><blockquote>Активное сопротивление и ёмкость <em>RC-</em>фильтра: <img width='484' height='24' src='page5_8_1_3/11_clip_image002_0002.gif'></blockquote>"

 var t4 ="<class='text'>Для получения лучшего сглаживания выходного напряжения после <em>С</em>-фильтра подсоединяют ещё <em>Г</em>-образное <em>LC</em>-звено. Получившийся <em>П</em>-образный <em>CLC</em>-фильтр (рис. 5.25, <em>д </em>) рассчитывают как двухзвенный: <em>k</em><em class='indexsmaldigit'>с </em> = <em class='index'>k</em><em class='indexsmall'>с</em><span class='indexsmaldigit'>1</span><span class='index'><em>k</em></span><em><span class='indexsmall'>с</span></em><span class='indexsmaldigit'>2</span>; <em>LС</em><span class=indexsmalldigit>2</span> <span class='symbol'><em>»</em></span><em> k<span class='indexsmall'>с</span></em><span class='indexsmaldigit'>2</span>/(<em>n<span class='symbol'>w</span></em>)<span class='indexBIGEST'>2</span>. Из последнего равенства находят <em>L</em>, задаваясь <em>С</em><span class='indexsmaldigit'>2</span> . Ёмкость <br><em>C</em><span class='indexsmaldigit'>1</span> <em class='symbol'>» </em>2<em>k</em><em class='indexsmall'>C</em><span class='indexsmaldigit'>1</span>/<em>n<span"+
 "<em><span class='symbol'>w</span>R</em> </em>или выбирают равной <em>С</em><span class='indexsmaldigit'>2</span>."


Text[0]=[":: Одноэлементный С-фильтр ::",t0]
Text[1]=[":: Одноэлементный L-фильтр. ::",t1]
Text[2]=[":: LС-фильтр ::",t2]
Text[3]=[":: RC-фильтр ::",t3]
Text[4]=[":: CLC-фильтр ::",t4]


Style[0]=["white","black","black","#F8F4F1","","","center","","","Verdana","center","",2,2,"80%",,1,20,0,10,51,1,100,"complex","gray"]

applyCssFilter()

