/*
Please refer to readme.html for full Instructions

Text[...]=[title,text]

Style[...]=[TitleColor,TextColor,TitleBgColor,TextBgColor,TitleBgImag,TextBgImag,TitleTextAlign,TextTextAlign, TitleFontFace, TextFontFace, TipPosition, StickyStyle, TitleFontSize, TextFontSize, Width, Height, BorderSize, PadTextArea, CoordinateX , CoordinateY, TransitionNumber, TransitionDuration, TransparencyLevel ,ShadowType, ShadowColor]
*/
//<link href="../../../mainpage.css" rel="stylesheet" type="text/css">
var FiltersEnabled = 1 // if your not going to use transitions or filters in any of the tips set this to 0
 var t0 ="<span class='head1'><span style='font-size:14pt;font-family:Arial;color:darkblue;'><b>Электрическая цепь <span style='font-size:12pt;font-family:Arial;color:black'> &#8211; это совокупность устройств и объектов, образующих путь для электрического тока, электромагнитные процессы в которых могут быть описаны с помощью понятий об электродвижущей силе, токе и напряжении."
 var t1 ="<span class='text'><span class=lac'head1'><span style='font-size:14pt;font-family:Arial;color:darkblue'><b>Электрический ток проводимости <span style='font-size:12pt;font-family:Arial;color:black'> &#8211; явление направленного движения свободных носителей электрического заряда <i>q</i> в веществе или в пустоте, количественно характеризуемое скалярной величиной, равной производной по времени от электрического заряда, переносимого свободными носителями заряда сквозь рассматриваемую поверхность, т. е. </span><table width='100%' border='0'>  <tr>    <td height='31'><div align='left' class='h3'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <strong><b><img width='160' height='39' src='page11/clip_image002_0000.jpg'></strong></div></td>"+
"<td class='head1'><div align='right' class='head1'><b><big>(1.1)</div></td></tr></table><span class='head1'><span style='font-size:12pt;font-family:Arial'><b>Из выражения (1.1) получим единицу тока [ <i>I</i> ] = [<i> q</i> ]/[ <i>t</i> ] = Кл/c = A&#183;c/c = A (ампер). </p>"
  var t2 ="<p class='text'><span class='head1'><span style='font-size:14pt;font-family:Arial;color:darkblue;'><b>Электрический ток переноса <span style='font-size:12pt;font-family:Arial;color:black'> &#8211; электрический ток, осуществляемый переносом электрических зарядов телами, количественно характеризуемый скалярной величиной, равной производной по времени от электрического заряда, переносимого телами сквозь рассматриваемую поверхность.</p>"
   var t3 ="<span class='head1'><span style='font-size:14pt;font-family:Arial;color:darkblue;'><b>Электрический ток смещения<span style='font-size:12pt;font-family:Arial;color:black'> &#8211; совокупность электрического тока смещения в пустоте и электрического тока поляризации диэлектрика, количественно характеризуемая скалярной величиной, равной производной по времени от потока электрического смещения <i>DS</i> сквозь рассматриваемую поверхность <i>S</i>, т. е.<br>&#160;&#160;&#160;&#160;&#160;&#160;&#160;<img src='page11/clip_image002_0001.jpg' width='202' height='37' align='top'><br>где <i>D </i>&#8211;электрическое смещение.</p>"
    var t4 ="<p class='text'><span class='head1'><span style='font-size:14pt;font-family:Arial;color:darkblue;'><b>Полный электрический ток <span style='font-size:12pt;font-family:Arial;color:black'>&#8211;  скалярная величина, равная сумме электрического тока проводимости, электрического тока переноса и электрического тока смещения сквозь рассматриваемую поверхность.</p>"
 var t5 ="<p class='text'><span class='head1'><span style='font-size:14pt;font-family:Arial;color:darkblue;'><b>Постоянный электрический ток <span style='font-size:12pt;font-family:Arial;color:black'>(в дальнейшем ток) &#8211; это неизменное и однонаправленное движение заряженных частиц (зарядов). При постоянном токе в течение каждого одинакового промежутка  времени &#916;<i>t </i>переносится  одинаковый заряд &#916;<i>q</i>. Поэтому ток <i>I</i> = <i>q</i>/<i>t</i>, где <i>q</i> - весь заряд  в кулонах (Кл) за  время <i>t</i> (с). </p>"
var t6 ="<span class='text'><span class='head1'><span style='font-size:14pt;font-family:Arial;color:darkblue;'><b>Условное положительное направление тока<i> I</i><span style='font-size:12pt;font-family:Arial;color:black'> во внешней (от источника энергии) цепи противоположно направлению движения потока электронов (электрон &#8211; частица, обладающая наименьшим отрицательным зарядом (<i>q</i><span class='indexsmall'><b>e</span></b> = -1,602<span class='symbol'>Ч</span>10<span class='stepen'><b><big>-</big>19</b></span> Кл, тогда 1 Кл = 6,24<span class='symbol'>Ч</span>10<span class='stepen'>18</span>  электронов)), т. е. он протекает от точки с большим потенциалом к точке с меньшим потенциалом, вызывая падение электрического напряжения (в дальнейшем &#8211; напряжение) на сопротивлении этого участка, т. е. <br></b>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<em>U</em><span class='indexsmall'><b>ab</b></span> = &#966;<span class='indexsmall'><b>a</b></span> &#8211; &#966;<span class='indexsmall'><b>b</b></span>."+"<div align='right'><span style='position:relative;top:-12pt'><span class='head1'><b><big>(1.2)</span></div>"
var t7 ="<span class='text'><span class='head1'><span style='font-size:14pt;font-family:Arial;color:darkblue;'><b>Потенциал электрический <span style='font-size:12pt;font-family:Arial;color:black'>&#966;<span class='indexsmall'><b>a</b></span> точки <i>а</i> &#8211; работа, которую нужно выполнить, чтобы перенести единицу заряда (1&nbsp;Кл)  из данной точки в бесконечность (где нет электрического поля ), т. е.</span><table width='100%'  border='0'>  <tr>    <td>&nbsp;&nbsp;&nbsp;<img src='page11/clip_image002_0007.gif' width='164' height='62'><img src='page11/clip_image002_0008.gif' width='99' height='62'></td>    <td><div align='right'><span class='head1'><span style='position:relative;top:-12pt'><big>(1.3)</span></div></td>  </tr></table>"+"<span class='head1'><span style='font-size:12pt;font-family:Arial'><b>где  <img src='page11/clip_image002_0006.gif' width='18' height='24' align='absmiddle'><span style='font-size:12pt;font-family:Arial'> &#8211; напряжённость (вектор) электрического поля, численно равная отношению силы, действующей на заряженную частицу, к значению её заряда. Из этого определения получают единицу напряжённости<br><span style='position:relative;top:3pt'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; [<i>E</i>] = [H]/[Кл] = В<span class='symbol'>Ч</span>А<span class='symbol'>Ч</span>с/м<span class='symbol'>Ч</span>A<span class='symbol'>Ч</span>c = В/м (вольт на метр).<span style='position:relative;top:3pt'><br>&#160;</span>"
var t8 ="<span class='text'><span class='head1'><span style='font-size:14pt;font-family:Arial;color:darkblue'><b>Напряжение <span style='font-size:12pt;font-family:Arial;color:black'>&#8211; это работа, затрачиваемая на перенос единицы заряда (1&nbsp;Кл) из точки <i>а</i> в точку <i>b</i> поля с напряжённостью<img src='page11/clip_image002_0006.gif' width='18' height='24' align='absmiddle'>по произвольному пути и равная линейному интегралу напряженности электрического поля, т.е.</span><table width='100%'  border='0'>  <tr>    <td>&nbsp;&nbsp;&nbsp;<img src='page11/clip_image002_0009.gif' width='99' height='50' align='middle'>.</td>    <td><div align='right'><span class='head1'><span class='head1'><span style='position:relative;top:-12pt'><big>(1.4)</span></div></td>  </tr></table><span class='head1'><span style='font-size:12pt;font-family:Arial'><b>Однозначно определяют только разность потенциалов (напряжение) между соответствующими точками. Когда говорят о потенциале точки электрической цепи, то подразумевают разность потенциалов между этой точкой и другой (обычно заземлённой), потенциал которой принимают равным нулю. Из определения (1.4) получают единицу напряжения (потенциала) <br><span style='position:relative;top:3pt'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[<i>U</i>] = [В/м]<span class='symbol'>Ч</span>[м] = B (вольт). <span style='position:relative;top:3pt'><br>&#160;</span>"
   var t9 ="<p class='text'><span class='head1'><span style='font-size:14pt;font-family:Arial;color:darkblue'><b>Электродвижущая сила <i>E</i> <span style='font-size:12pt;font-family:Arial;color:black'>(в дальнейшем ЭДС <i>E</i>) &#8211; скалярная величина, характеризующая способность стороннего поля и индуктированного электрического поля вызывать электрический ток. ЭДС <i>Е</i> численно равна работе (энергии) <i>W</i> в джоулях (Дж), затрачиваемой этим полем на перемещение единицы заряда (1 Кл) из одной точки поля в другую.  Из этого определения получим единицу ЭДС <br><span style='position:relative;top:3pt'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[<i>E</i>] = [<i>W</i>]/[<i>q</i>] = Дж/Кл = В&#183;А&#183;с/А&#183;с = В (вольт).<br><span style='position:relative;top:3pt'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Тогда напряжение> (разность потенциалов) 1 В равно 1 Дж энергии для перемещения 1 Кл заряда  из одной точки проводника в другую.<span style='position:relative;top:3pt'><br>&#160;</span>"

Text[0]=[":: <b>Электрическая цепь ::",t0]
Text[1]=[":: <b>Электрический ток проводимости ::",t1]
Text[2]=[":: <b>Электрический ток переноса ::",t2]
Text[3]=[":: <b>Электрический ток смещения ::",t3]
Text[4]=[":: <b>Полный электрический ток ::",t4]
Text[5]=[":: <b>Постоянный электрический ток ::",t5]
Text[6]=[":: <b>Условное положительное направление тока ::",t6]
Text[7]=[":: <b>Потенциал электрический ::",t7]
Text[8]=[":: <b>Напряжение ::",t8]
Text[9]=[":: <b>Электродвижущая сила  (ЭДС) ::",t9]

Style[0]=["white","#ffdeed","#8800ff","white","","","center","","","Verdana","center","",3,3,"100%",,1,30,10,30,51,1,,"complex","gray"]

applyCssFilter()

