/*
Please refer to readme.html for full Instructions

Text[...]=[title,text]

Style[...]=[TitleColor,TextColor,TitleBgColor,TextBgColor,TitleBgImag,TextBgImag,TitleTextAlign,TextTextAlign, TitleFontFace, TextFontFace, TipPosition, StickyStyle, TitleFontSize, TextFontSize, Width, Height, BorderSize, PadTextArea, CoordinateX , CoordinateY, TransitionNumber, TransitionDuration, TransparencyLevel ,ShadowType, ShadowColor]
*/
var FiltersEnabled = 1 // if your not going to use transitions or filters in any of the tips set this to 0
 var t0 ="<span class='head2'>Построим ВД</span> в соответствии с уравнением (3.34). Начнём построение с вектора тока , который откладываем, как и вектор напряжения вдоль оси ох. Вектор напряжения отстаёт от<span class='head2'> вектора </span>"
 var t1 ="<span class='head2'>Электрический ток</span> (в дальнейшем <span class='head2'>ток</span>) - явление направленного движения свободных носителей электрического заряда в веществе или в вакууме. Численно электрический ток определяется как скорость изменения заряда <span class='index'>Q</span> в течение данного интервала времени <span class='index'>t</span></i>, т. е.</p><p><img width=147 height=48 src='images/image003.gif'> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span><span class='head2'>(1.1)</span></p>"
  var t2 ="<span class='head2'>Постоянный ток</span> - это неизменное и однонаправленное движение заряжен­ных частиц (зарядов). При постоянном токе в течение каждого одинакового промежутка времени <img width=31 height=21 src='images/image005.gif'> переносится одинаковый заряд <img width=36 height=28 src='images/image007.gif'>.Поэтому ток <img width=76 height=27 src='images/image009.gif'> где <span class='index'>Q</span> - весь заряд в кулонах (Кл) за время <span class='index'>t</span> (c)"
   var t3 ="<span class='head2'>Потенциал электрического поля</span> равен работе, затрачивамой электрическим полем при переносе единичного заряда (<span class='index'>Q</span> = 1 Кл) из данной точки в бесконечность (где нет электрического поля), т. е<br><img width=169 height=64 src='images/image017.gif' >, <img width=88 height=60 src='images/image019.gif'>, (1.2)<br>где <img width=19 height=23 src='images/image021.gif' > - напряженность (вектор) электрического поля, численно равная отношению силы, действующей на заряженную частицу, к ее заряду.<br><span class='head2'>ПРИМЕЧАНИЕ.</span> Однозначно определяется только разность потенциалов (напряжение) между соответствующими точками. Когда говорят о потенциале точки электрической цепи, то подразумевают разность потенциалов между этой точкой и другой (обычно заземленной), потенциал которой принимают равным нулю."
    var t4 ="<span class='head2'>Падение напряжения</span><span class='text'>  (в дальнейшем </span><span class='head2'>напряжение</span><span class='text'>) - это разность потенциалов на клеммах (зажимах) участка или элемента </span><span class='index'>ab</span><span class='text'> цепи, по которому протекает ток от точки с большим потенциалом </span><span class='index'>j</span><span class='indexsmall'>a</span><span class='text'> к точке с меньшим потенциалом </span><span class='index'>j</span><span class='indexsmall'>b</span><span class='text'>, т. е.</span></p><p><img width=114 height=36 src='images/image011.gif'> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span class='head2'> (1.3)" + 
  "</span></p><p><span class='text'>Другими словами, напряжение </span><span class='index'>U</span><span class='indexsmall'>ab </span><span class='text'>- это работа, затра­чиваемая на перенос единичного заряда (1 Кл) из точки </span><span class='index'>a</span><span class='text'> в точку </span><span class='index'>b</span><span class='text'> электрического поля по произвольному пути и равная линейному интегралу напряженности </span><img width=18 height=26 src='images/image013.gif'>электрического поля вдоль этого пути, т. е.<br><img width=116 height=68    src='images/image015.gif'> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class='head2'>(1.4)</span>"
   var t5 ="<span class='head2'>Электродвижущая сила (ЭДС)</span> - скалярная величина, характеризующая способность стороннего (или индуцированного электрического) поля вызывать электрический ток и численно равная работе (энергии) <span class='index'>W</span> в джоулях (Дж), затрачиваемой этим полем на перемещения единицы заряда (1 Кл) из одной точки поля в другую.<br>Сторонней ЭДС называется сила неэлектростатического происхождения (механическая, химическая, электромагнитная и др.), производящая разделение зарядов. Работа, совершаемая в цепи при прохождении электрического тока, равна работе сторонних ЭДС."
var t6="Под </span><span class='head2'>резонансом</span><span class='text'> понимают такой режим работы электрической цепи, содержащей индуктивные            и ёмкостные элементы, при котором её входное сопротивление имеет чисто             активный характер, и, следовательно, сдвиг фаз между напряжением и             током на входе равен нулю (</span><span class='index'>j</span><span class='text'>             = 0). Разнородные реактивные сопротивления (проводимости) цепи полностью             компенсируют друг друга. Реактивная мощность </span><span class='index'>Q</span><span class='text'>             цепи при этом равна нулю.<br>            Цепи, в которых возникают резонансные явления, называют резонансными             цепями или колебательными контурами. Простейший колебате -<br>            </span>"

Text[0]=[":: Электрическая цепь ::",t0]
Text[1]=[":: Электрический ток ::",t1]
Text[2]=[":: Постоянный ток ::",t2]
Text[3]=[":: Потенциал электрического поля ::",t3]
Text[4]=[":: Падение напряжения (напряжение) ::",t4]
Text[5]=[":: Электродвижущая сила  (ЭДС) ::",t5]
Text[6]=[":: Бе-бе ::",t6]

Style[0]=["white","black","black","#F8F4F1","","","center","","","Arial","center","",2,2,"80%",,1,20,0,10,51,1,80,"complex","gray"]

applyCssFilter()

